2022-12-12 00:04:19,943 : INFO : start analyzing file
2022-12-12 00:04:19,959 : ERROR : path provided not found: [Errno 2] No such file or directory: 'C:\\Users\\dorge\\neolithics\\saved_results\\det_2022-12-12_000131_5523654.txt.txt'
Traceback (most recent call last):
  File "C:\Users\dorge\neolithics\eye_analyzer\analyzer.py", line 233, in read_results
    with open(self.save_txt_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dorge\\neolithics\\saved_results\\det_2022-12-12_000131_5523654.txt.txt'
